autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

replicaCount: 1

serviceAccount:
  create: true
  name: ""

backend:
  image:
    repository: doadores-backend
    tag: latest
  service:
    port: 5000
  env:
    DB_HOST: mysql
    DB_USER: root
    DB_PASS: root
    DB_NAME: projetoDevOps

frontend:
  image:
    repository: doadores-frontend
    tag: latest
  service:
    port: 80

mysql:
  image:
    repository: mysql
    tag: 8.0
  rootPassword: root
  database: projetoDevOps
  service:
    port: 3306
  volumeMountPath: /docker-entrypoint-initdb.d
  initScriptHostPath: ./db-init/init.sql
  volumeClaim:
    storage: 1Gi

ingress:
  enabled: true
  hosts:
    - host: k8s.local
      paths:
        - path: /
          backend: frontend
        - path: /api
          backend: backend
  tls: []
